// Copyright © 2018. All rights reserved.
// Author: Alice Qio.
// Contacts: <qioalice@gmail.com>.
// License: https://opensource.org/licenses/MIT
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom
// the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.

package tgbot

import (
	api "github.com/go-telegram-bot-api/telegram-bot-api"
)

// FViewSuccessFinisher is the alias to function (callback) that will be called,
// when message generated by ctx context will be successfully sent.
// Associated context and API object of the sent message will be passed
// to the callback.

// FViewSuccessFinisher is the alias to function (callback), which receives
// an info of sent Telegram message (API response) and standard context object
// (TCtx) by which the sent message was created.
//
// If you need to pass your own context object (extended context),
// the signature of callback must be the same as this but you can use
// your context type (the same as the your default context -> extended context
// converter registered using TBot.ExtendContext method).
//
// For example:
// type FViewSuccessCustomFinisher func(ctx *T, err error)
//
// More info: tViewSuccessFinisher, TCtx, tSender, TBot.ExtendContext.
type FViewSuccessFinisher func(ctx *TCtx, sent *api.Message)
